---
title: "EDA"
format:
  html:
    toc: true
    embed-resources: true
    theme: yeti
    code-fold: true
execute:
  echo: true
---

# EDA
## Introduction
## Code

### Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns  
import math

In [ ]:
# Data Loading
pd.set_option('display.max_columns', None)

df = pd.read_csv('../../data/rawdata/T_DB1B_MARKET_CLEAN.csv')   

# Data Overview
print("Data Loaded")
print(df.shape)
df.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9408\2164937600.py:4: DtypeWarning: Columns (6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../../data/rawdata/T_DB1B_MARKET_COMBINED.csv')

Data Loaded
(32343186, 17)

,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,REPORTING_CARRIER,TICKET_CARRIER,OPERATING_CARRIER,BULK_FARE,PASSENGERS,MARKET_FARE,MARKET_DISTANCE,DISTANCE_GROUP,MARKET_MILES_FLOWN,NONSTOP_MILES,MKT_GEO_TYPE
0,10135,1013506,30135,10136,1013603,30136,OH,AA,99,0.0,1.0,895.41,1575.0,4.0,1575.0,1458.0,2.0
1,10135,1013506,30135,10140,1014005,30140,9E,DL,99,0.0,1.0,168.50,1961.0,4.0,1961.0,1738.0,2.0
2,10135,1013506,30135,10140,1014005,30140,9E,DL,99,0.0,1.0,201.84,1961.0,4.0,1961.0,1738.0,2.0
3,10135,1013506,30135,10140,1014005,30140,9E,DL,99,0.0,1.0,361.50,1961.0,4.0,1961.0,1738.0,2.0
4,10135,1013506,30135,10140,1014005,30140,9E,DL,99,0.0,1.0,843.00,1961.0,4.0,1961.0,1738.0,2.0

In [ ]:
# Data Structure
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32343186 entries, 0 to 32343185
Data columns (total 17 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ORIGIN_AIRPORT_ID      int64
 1   ORIGIN_AIRPORT_SEQ_ID  int64
 2   ORIGIN_CITY_MARKET_ID  int64
 3   DEST_AIRPORT_ID        int64
 4   DEST_AIRPORT_SEQ_ID    int64
 5   DEST_CITY_MARKET_ID    int64
 6   REPORTING_CARRIER      object
 7   TICKET_CARRIER         object
 8   OPERATING_CARRIER      object
 9   BULK_FARE              float64
 10  PASSENGERS             float64
 11  MARKET_FARE            float64
 12  MARKET_DISTANCE        float64
 13  DISTANCE_GROUP         float64
 14  MARKET_MILES_FLOWN     float64
 15  NONSTOP_MILES          float64
 16  MKT_GEO_TYPE           float64
dtypes: float64(8), int64(6), object(3)
memory usage: 4.1+ GB

,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,BULK_FARE,PASSENGERS,MARKET_FARE,MARKET_DISTANCE,DISTANCE_GROUP,MARKET_MILES_FLOWN,NONSTOP_MILES,MKT_GEO_TYPE
count,3.234319e+07,3.234319e+07,3.234319e+07,3.234319e+07,3.234319e+07,3.234319e+07,2.404532e+07,2.404532e+07,2.404532e+07,2.404532e+07,2.404532e+07,2.404532e+07,2.404532e+07,2.404532e+07
mean,1.282563e+04,1.282567e+06,3.196636e+04,1.282417e+04,1.282421e+06,3.196489e+04,8.442392e-05,1.904901e+00,2.684043e+02,1.308387e+03,3.114319e+00,1.305384e+03,1.227264e+03,1.930577e+00
std,1.544638e+03,1.544636e+05,1.378709e+03,1.545144e+03,1.545143e+05,1.378273e+03,9.187862e-03,4.927751e+00,2.205487e+02,8.216434e+02,1.672517e+00,8.201554e+02,7.781802e+02,2.541717e-01
min,1.013500e+04,1.013506e+06,3.000700e+04,1.013500e+04,1.013506e+06,3.000700e+04,0.000000e+00,1.000000e+00,0.000000e+00,1.100000e+01,1.000000e+00,0.000000e+00,1.100000e+01,1.000000e+00
25%,1.129800e+04,1.129806e+06,3.072100e+04,1.129800e+04,1.129806e+06,3.072100e+04,0.000000e+00,1.000000e+00,1.475000e+02,7.170000e+02,2.000000e+00,7.130000e+02,6.590000e+02,2.000000e+00
50%,1.291500e+04,1.291503e+06,3.170300e+04,1.290200e+04,1.290205e+06,3.170300e+04,0.000000e+00,1.000000e+00,2.285000e+02,1.090000e+03,3.000000e+00,1.089000e+03,1.023000e+03,2.000000e+00
75%,1.410700e+04,1.410702e+06,3.310500e+04,1.410700e+04,1.410702e+06,3.310500e+04,0.000000e+00,1.000000e+00,3.370000e+02,1.759000e+03,4.000000e+00,1.754000e+03,1.660000e+03,2.000000e+00
max,1.686900e+04,1.686902e+06,3.642200e+04,1.686900e+04,1.686902e+06,3.642200e+04,1.000000e+00,1.032000e+03,3.873500e+04,1.134400e+04,2.300000e+01,1.134400e+04,9.411000e+03,2.000000e+00

realized a lot of US airports have missing info