---
title: "EDA"
format:
  html:
    toc: true
    embed-resources: true
    theme: yeti
    code-fold: true
execute:
  echo: true
---

# EDA
## Introduction
## Code

### Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns  
import math

In [3]:
# Data Loading
pd.set_option('display.max_columns', None)

df = pd.read_csv('../../data/cleandata/T_DB1B_MARKET_CLEAN.csv')   

# Data Overview
print("Data Loaded")
print(df.shape)
df.head()

Data Loaded
(25072315, 23)

,YEAR,QUARTER,ORIGIN_AIRPORT_ID,ORIGIN,DEST_AIRPORT_ID,DEST,REPORTING_CARRIER,TICKET_CARRIER,OPERATING_CARRIER,BULK_FARE,PASSENGERS,MARKET_FARE,MARKET_DISTANCE,NONSTOP_MILES,MKT_GEO_TYPE,ORIGIN_LAT,ORIGIN_LON,DEST_LAT,DEST_LON,AIRCRAFT_FUEL,SALARIES_BENEFITS,LANDING_FEES,AIRCRAFT_TYPE
0,2024,3,10135,ABE,10136,ABI,MQ,AA,99,0.0,1.0,430.5,1575.0,1458.0,2,40.6521,-75.440804,32.411301,-99.681900,2355898.96,4347507.64,276249.56,NaN
1,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,309.5,1961.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001,2475281.00,4897224.00,279286.00,NaN
2,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,324.5,1961.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001,2475281.00,4897224.00,279286.00,NaN
3,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,378.5,1961.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001,2475281.00,4897224.00,279286.00,NaN
4,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,381.8,2580.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001,2475281.00,4897224.00,279286.00,NaN

In [4]:
# Data Structure
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25072315 entries, 0 to 25072314
Data columns (total 23 columns):
 #   Column             Dtype
---  ------             -----
 0   YEAR               int64
 1   QUARTER            int64
 2   ORIGIN_AIRPORT_ID  int64
 3   ORIGIN             object
 4   DEST_AIRPORT_ID    int64
 5   DEST               object
 6   REPORTING_CARRIER  object
 7   TICKET_CARRIER     object
 8   OPERATING_CARRIER  object
 9   BULK_FARE          float64
 10  PASSENGERS         float64
 11  MARKET_FARE        float64
 12  MARKET_DISTANCE    float64
 13  NONSTOP_MILES      float64
 14  MKT_GEO_TYPE       int64
 15  ORIGIN_LAT         float64
 16  ORIGIN_LON         float64
 17  DEST_LAT           float64
 18  DEST_LON           float64
 19  AIRCRAFT_FUEL      float64
 20  SALARIES_BENEFITS  float64
 21  LANDING_FEES       float64
 22  AIRCRAFT_TYPE      float64
dtypes: float64(13), int64(5), object(5)
memory usage: 4.3+ GB

,YEAR,QUARTER,ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID,BULK_FARE,PASSENGERS,MARKET_FARE,MARKET_DISTANCE,NONSTOP_MILES,MKT_GEO_TYPE,ORIGIN_LAT,ORIGIN_LON,DEST_LAT,DEST_LON,AIRCRAFT_FUEL,SALARIES_BENEFITS,LANDING_FEES,AIRCRAFT_TYPE
count,2.507232e+07,2.507232e+07,2.507232e+07,2.507232e+07,25072315.0,2.507232e+07,2.507232e+07,2.507232e+07,2.507232e+07,2.507232e+07,2.507232e+07,2.507232e+07,2.507232e+07,2.507232e+07,2.469864e+07,2.469864e+07,2.469864e+07,1.423626e+07
mean,2.024483e+03,2.559592e+00,1.280349e+04,1.280288e+04,0.0,1.736275e+00,2.726650e+02,1.140368e+03,1.072340e+03,1.954911e+00,3.665510e+01,-9.431765e+01,3.667802e+01,-9.430822e+01,1.795146e+06,3.799370e+06,2.378504e+05,6.398459e+02
std,4.996994e-01,1.104003e+00,1.548751e+03,1.549209e+03,0.0,3.242138e+00,1.236967e+02,6.843926e+02,6.503210e+02,2.074993e-01,6.058662e+00,1.783678e+01,6.050524e+00,1.784000e+01,7.068760e+05,1.377877e+06,9.251845e+04,5.636878e+01
min,2.024000e+03,1.000000e+00,1.013500e+04,1.013500e+04,0.0,1.000000e+00,1.901000e+01,1.100000e+01,1.100000e+01,1.000000e+00,-1.433100e+01,-1.766460e+02,-1.433100e+01,-1.766460e+02,3.674660e+03,1.227674e+04,7.296400e+02,3.500000e+01
25%,2.024000e+03,2.000000e+00,1.129200e+04,1.129200e+04,0.0,1.000000e+00,1.795000e+02,6.370000e+02,5.990000e+02,2.000000e+00,3.289680e+01,-1.107380e+02,3.289680e+01,-1.107380e+02,1.325905e+06,3.393836e+06,1.937480e+05,6.120000e+02
50%,2.024000e+03,3.000000e+00,1.294500e+04,1.294500e+04,0.0,1.000000e+00,2.530000e+02,9.890000e+02,9.290000e+02,2.000000e+00,3.736260e+01,-8.790480e+01,3.736260e+01,-8.790480e+01,2.127674e+06,4.419047e+06,2.666545e+05,6.140000e+02
75%,2.025000e+03,4.000000e+00,1.410700e+04,1.410700e+04,0.0,1.000000e+00,3.470000e+02,1.502000e+03,1.415000e+03,2.000000e+00,4.077720e+01,-8.094310e+01,4.077720e+01,-8.094310e+01,2.355899e+06,4.652768e+06,2.933110e+05,6.940000e+02
max,2.025000e+03,4.000000e+00,1.642200e+04,1.642200e+04,0.0,4.930000e+02,6.472500e+02,6.383000e+03,5.981000e+03,2.000000e+00,7.128540e+01,1.457290e+02,7.128540e+01,1.457290e+02,2.675828e+06,5.221803e+06,3.640015e+05,8.890000e+02

realized a lot of US airports have missing info