In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns  
import math

df = pd.read_csv('/Volumes/Extreme Pro/DSAN-5200/final-project/T_DB1B_MARKET_CLEAN.csv')

In [6]:
df.head()

,YEAR,QUARTER,ORIGIN_AIRPORT_ID,ORIGIN,DEST_AIRPORT_ID,DEST,REPORTING_CARRIER,TICKET_CARRIER,OPERATING_CARRIER,BULK_FARE,PASSENGERS,MARKET_FARE,MARKET_DISTANCE,NONSTOP_MILES,MKT_GEO_TYPE,ORIGIN_LAT,ORIGIN_LON,DEST_LAT,DEST_LON
0,2024,3,10135,ABE,10136,ABI,MQ,AA,99,0.0,1.0,430.5,1575.0,1458.0,2,40.6521,-75.440804,32.411301,-99.681900
1,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,148.5,1961.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001
2,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,182.0,1961.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001
3,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,309.5,1961.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001
4,2024,3,10135,ABE,10140,ABQ,9E,DL,99,0.0,1.0,324.5,1961.0,1738.0,2,40.6521,-75.440804,35.040199,-106.609001

In [7]:
df = df[['ORIGIN', 'DEST', 'MARKET_FARE', 'MARKET_DISTANCE']]
df.head()

  ORIGIN DEST  MARKET_FARE  MARKET_DISTANCE
0    ABE  ABI        430.5           1575.0
1    ABE  ABQ        148.5           1961.0
2    ABE  ABQ        182.0           1961.0
3    ABE  ABQ        309.5           1961.0
4    ABE  ABQ        324.5           1961.0

In [8]:
df.to_csv('/Volumes/Extreme Pro/DSAN-5200/final-project/origin_dest_price.csv', index=False)

In [9]:
df["ROUTE"] = df["ORIGIN"] + "-" + df["DEST"]

In [10]:
route_summary = (
    df.groupby("ROUTE")
    .agg(
        avg_fare=("MARKET_FARE", "mean"),
        median_fare=("MARKET_FARE", "median"),
        min_fare=("MARKET_FARE", "min"),
        max_fare=("MARKET_FARE", "max"),
        std_fare=("MARKET_FARE", "std"),
        avg_distance=("MARKET_DISTANCE", "mean"),
        num_observations=("MARKET_FARE", "count")
    )
    .reset_index()
)

In [11]:
route_summary[["ORIGIN", "DEST"]] = route_summary["ROUTE"].str.split("-", expand=True)

In [12]:
route_summary.to_csv('/Volumes/Extreme Pro/DSAN-5200/final-project/route_summary.csv', index=False)

In [13]:
route_summary.head()

,ROUTE,avg_fare,median_fare,min_fare,max_fare,std_fare,avg_distance,num_observations,ORIGIN,DEST
0,ABE-ABI,662.955000,662.955,430.5,895.41,328.741014,1575.00,2,ABE,ABI
1,ABE-ABQ,367.225400,333.500,137.5,993.00,183.186048,1907.61,100,ABE,ABQ
2,ABE-ABR,432.000000,432.000,432.0,432.00,NaN,1856.00,1,ABE,ABR
3,ABE-ABY,449.772000,438.500,217.5,817.00,150.277381,837.00,15,ABE,ABY
4,ABE-AEX,384.166667,328.500,242.5,811.50,168.564528,1192.00,9,ABE,AEX